### PR TITLE
correct linear drift when trimming clk100ns in ubertooth_rx

### PR DESCRIPTION
**Pull request by elli89**
This is related to #214. I have successfully tested the patch with different Ubertooth sticks whose clocks drifted in different directions.

### CODE REVIEW

**Comment by jbmontgomery4** [comment]
Pulled changes yesterday(07/18/2016). Did not see any improvement. clk_offset is jumping all over the place. Same behavior using 2 Ubertooths. Maybe the problem is I don't know what to expect. My thinking is that the clock_offset should settle.

Thanks,
John Montgomery

**Comment by elli89** [comment]
@jbmontgomery4 thanks for testing! You're right. clock_offset should get corrected and set to 2250. The drift of clock_offset is supposed to slow down so the clock needs to be trimmed only once in ~40 seconds. I tested it with an Ubertooth stick whose crystal was mistuned by changing its capacitors so the clock drifts by 22 ppm. Could you upload a log file as you did in #214?

**Comment by jbmontgomery4** [comment]
What environment are you using? Just wondering. I am running one ubertooth connected to a laptop running debian. I am running another ubertooth connected to a windows PC running debian on VirtualBox. I will provide you files from both.

**Comment by elli89** [comment]
I am running Manjaro on a laptop. I also have a virtual machine with Ubuntu 14.04 but I did not test Ubertooth with it, yet.

**Comment by jbmontgomery4** [comment]
From the VirtualBox using command:

ubertooth-rx -l e8a14a -u e8 (test.txt)

ubertooth-rx -l e8a14a -u e8 -s (test_s.txt)

[test.txt](https://github.com/greatscottgadgets/ubertooth/files/372231/test.txt)
[test_s.txt](https://github.com/greatscottgadgets/ubertooth/files/372232/test_s.txt)

**Comment by jbmontgomery4** [comment]
From laptop using the same commands as in previous comment.

[laptop_test.txt](https://github.com/greatscottgadgets/ubertooth/files/372258/laptop_test.txt)
[laptop_test_s.txt](https://github.com/greatscottgadgets/ubertooth/files/372257/laptop_test_s.txt)

**Comment by elli89** [comment]
I see the problem. Currently libubertooth receives USB packets from the stick in groups of eight packets. This behaviour is set by PKTS_PER_XFER in ubertooth_control.h

When the clock is out of sync, libubertooth does not trim it instantly. It waits for eight packets in a row, whose clock is out of sync. If it trimmed it instantly, there could be seven other packets in the receiver queue whose clock is also out of sync. So the clock trimming procedure would be performed once for each packet in the queue.

In your case the clock is drifting quite fast so it completely turns around while you receive eight out-of-sync packets. Since the clock correction is based on the clock difference of the last received packet, libubertooth performs an incorrect trim.

#219 should fix this issue by processing the USB packets one by one rather than processing them in groups of eight. So you could try using my branch libusb_thread.

You could also try to set PKTS_PER_XFER to a lower value (2 worked for me). If you do so, be sure to also adjust BANK_LEN to (SYM_LEN * 8) instead of (SYM_LEN * PKTS_PER_XFER).

**Comment by jbmontgomery4** [comment]
Tried using your branch libusb_thread and saw no change.

**Pull request merged**
