### PR TITLE
make python files compatible with python 3

### PR DESCRIPTION
**Pull request by elli89**
Some changes to make my life easier since I'm using arch linux which uses python 3 by default. The changes should still be compatible with Python 2 (I have run a quick test). Most changes are print statements with parentheses.

Could you please recheck my changes in the buffer handling in Ubertooth.py? Python 3 does not allow implicit casts from bytearray to string so I had to eliminate the data variable.

Thanks!
Hannes

### CODE REVIEW

**Comment by dominicgs** [comment]
The ubertooth-specan changes look good and I've tested them under python 2 and 3.

The extcap code gives the following error when listing interfaces using python 3:
```
$ python3 btle-extcap.py  --list-interfaces
Traceback (most recent call last):
  File "btle-extcap.py", line 149, in <module>
    main()
  File "btle-extcap.py", line 60, in main
    list_interfaces()
  File "btle-extcap.py", line 101, in list_interfaces
    lines = out.split('\n')
TypeError: 'str' does not support the buffer interface
```

**Comment by elli89** [comment]
Right, I forgot to append 'universal_newlines=True' to the subprocess constructor. Here's the patch.

**Comment by dominicgs** [comment]
Tested, works for me. I'll merge this now.

**Comment by elli89** [comment]
Thanks, Dominic!

**Pull request merged**
