### PR TITLE
Adding libstdc++-arm-none-eabi-newlib dependency to README

### PR DESCRIPTION
**Pull request by scottdarch**
Per #91 adding extra instructions for building firmware.

PTAL @dominicgs

### CODE REVIEW

**Comment by mikeryan** [comment]
I've never had to explicitly request this package when using recent versions of Debian and Ubuntu. What version of Debian/Ubuntu are you on?

**Comment by scottdarch** [comment]
Ubuntu 14.1

**Comment by dominicgs** [comment]
I think the problem is that we have ```-lstdc++ -lsupc++``` in our LDFLAGS, which isn't required for anything other than the bootloader.

**Comment by dominicgs** [comment]
I have solved this by removing ```-lstdc++ -lsupc++``` from the LDFLAGS.  I have added a not about installing this for the bootloader build to the bootloader's readme file.

**Comment by dominicgs** [comment]
@scottdarch Thanks for raising the issue with us!

**Pull request closed without merging**
