### PR TITLE
use a libusb event handling thread in libubertooth

### PR DESCRIPTION
**Pull request by elli89**
This patch moves the libusb polling procedure to a separate thread. That way, USB packets can be received from the Ubertooth stick even while the host program is busy. The event handling thread stores received USB packets in a threadsafe FIFO buffer (see #216). When the main thread is not busy, it takes a packet from the FIFO and processes it.

Please also have a look at issue #218 which addresses the case of FIFO overflows.

### CODE REVIEW

**Comment by jbmontgomery4** [comment]
According to your changes, it is my understanding you want to use libusb_handle_events() in a separate event handling thread. However, the documentation that was referenced designates that:

int libusb_handle_events	(libusb_context *ctx	)	

**This function is kept primarily for backwards compatibility. All new code should call libusb_handle_events_completed() or libusb_handle_events_timeout_completed() to avoid race conditions.**

However, I do agree with the FIFO. 

Use:

libusb_alloc_transfer to allocate a libusb_transfer
libusb_fill_bulk_transfer to fill the transfer designating a callback (asynchronous) and a buffer from the fifo.
libusb_submit_transfer to start the transfers
main thread will wait for a complete transfer using libusb_handle_events_completed
process all received packets

In the callback (called asynchronously):

if transfer is complete:
    assign next fifo buffer to the libusb_transfer
    use libusb_submit_transfer for the next transfer
    indicate transfer complete to the main loop

**Comment by dominicgs** [comment]
@elli89 Am I right in assuming that this replaces PR #216?  i.e. it contains all of the FIFO changes?

My only real concern here is the combination of pthreads + Windows as we've been moving towards better Windows compatibility.  I'm willing to ignore that concern for now if this significantly improves things for users.

@jbmontgomery4 Historically we've tried to support the greatest number of users by limiting ourselves to libUSB calls from older versions, hence the existing call to `int libusb_handle_events (libusb_context *ctx )`.  So that piece of legacy-ish code is on me.
However, I think you make a good point and the call to `libusb_handle_events_completed()` was added in 1.0.9, which should be available on most systems at this point. I'd be happy to adjust this after merging this PR.

**Comment by elli89** [comment]
@dominicgs  right, this PR contains all the changes of PR #216 and thus replaces that PR.

**Comment by elli89** [comment]
Since there are currently merge conflicts, I will rebase this branch onto the current master.

**Comment by dominicgs** [comment]
Did you already rebase this?  I don't see merge conflicts but git timestamps are confusing me.

**Comment by mcummings1** [comment]
Hello all, a little new to git and to working directly with the ubertooth code, but I thought I would throw my two cents in on this latest change. Late yesterday, I manually added these latest changes to the ubertooth-master stream and ran ubertooth-rx -s for about seven hours without a failure. Obviously, I did get a number of dropped packets but, as elli89 said above, dropped messages are significantly better than the program aborting, at least in my case. Previous to this alteration, I wrote some code to monitor the output and restart the application as necessary to keep the stream flowing - this is definitely a step forward.

I do plan on doing a bit more research, just for my own edification if nothing else, to see how frequently packets get dropped and if the drops correlate to anything external to the rf environment (i.e., other jobs running on the processor, etc.).

Thanks for all of the work you have all done on this project - very much appreciated! Finally, my apologies in advance if these comments are in the wrong location or are off base.


Respectfully,
Marshall

**Comment by elli89** [comment]
Yes, I already rebased it. Sorry for the timestamp confusion.

Aside, I will be on vacation for a week and won't be able to read my mails until the 2nd of August.

Best whishes!

Hannes

**Comment by dominicgs** [comment]
I committed a change yesterday that conflicts with this, so now it won't merge cleanly again.  I'll fix it now.

Enjoy your vacation.

**Pull request merged**
